export const ADD_COLUMN = 'ADD_COLUMN';
export const REMOVE_COLUMN = 'REMOVE_COLUMN';

export const ADD_TASK_ID = 'ADD_TASK_ID';
export const REMOVE_TASK_ID = 'REMOVE_TASK_ID';

export const SWITCH_TASKS_ORDER_IN_THE_SAME_COLUMN = 'SWITCH_TASKS_ORDER_IN_THE_SAME_COLUMN';
export const SWITCH_TASKS_ORDER_IN_THE_DIFFERENT_COLUMNS = 'SWITCH_TASKS_ORDER_IN_THE_DIFFERENT_COLUMNS';

export const RENAME_COLUMN = 'RENAME_COLUMN';